language: java
addons:
  sonarcloud:
    organization: "mihanloko"
    token:
      secure: "mqdoawEKQJX6OtLO7XDl+1BXXhmhp0s0dIJDlHNFcsig2JnmZ4hG5PtGOqsVUGTgNkHsNed3W8hEhmlU/zCh33LxJqzhXIwhx7G6oojMQEO2YOoVhcYvFhK+f9g50mwywTnTfZgViB6VVOPWwZ8VDO9gpCNEeM2e7WZ3KZESkb5/TcppZRaqYC9rs38+XNwqcXiWaylUCPsMoZuf+YKrNgmioHvYXCOHV/OdKbgZbqCvQ5fxV3jEqrDctnfAU5P6tnXS/GWsngdiveD8fTPYX7W6ESpdXq74YCrTeVyiqsUGmyJETVXtLG46IN4+zAibmn+QkSiHSAvarFBTW/4cAOd18qwyMxrMg3Zvjkz8eONIe8GUi9I43HD61+G294DtQjiE0laagyq3C2xFH6Nb9WwoWfD8Qe02vCcoMrp9Xm1bQeN37DNKeh6GlsjITU4AY+qWKC8S2AbzqgDaw15V1WCuJPo0CoKJgXjgtvw3C1MRrCcIcxpVwHNAhuo5RmPk40agX5JNek/xWIc7aARGavkc74bfD/2SQe+paaIocVRzQgjsAWOoRq50I4dDtUV2Y4DRQHD+dgY3w6dEpdlT9GsYfB0gP48md2pQOnoemhKWb7m6WXe+NAkPSCurBkTOjo7hLt3yQXpmiEPF6Dq7cOF4sqGtkHVVLA+FPvC/VaE="

script:
  - mvn clean package package org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=mihanloko_projectForTeamDev

deploy:
  provider: heroku
  app: test-app-loko
  api_key:
    secure: A6jkCxvVxNBt6mIaljaeS8pqAg72b7Qoy5wy6xZ8YRIa6Qw4BnmwLNyYB+CdoTc7prO8g8c+tHvZLDcmLX40mY4/B0WCAYi9C2gaXdyYYSOzVzn+Pa3FSc2WGeB6WynffBu7MTP7IltFp12zIYhYPzpZSYLO65voAq071qk0eR1vtEebvg4eES92aJOquXxe0aOqM0Npxf3LBsoUJDLtOuiI1ZlINudljPewqGllwEIwyi3yYr7NidoTmLs8oPGyiHetOnU61mRa8xOWXpOwBFzjLHOsGlKj5PXo3WFHSvx5kB6t9jpjEngdc8MhM1OEIPnbmDqYrwEr3PAw4w5UJ7RhZqQeG09RKKHJTNyglKDrCMGlPgdRsZ++Bq4LSHONcGIk3r+pHllZnGTJM2a7HdnEQqyVP/bav6ebQW1fe3fwA4kn80Pag8gMDVHj89VRH33voiYncHntCPCQqhvLthQWcVvSqSZdzIrUqExXXIfymtGgBwKTiw5LfztlSLVv+4jxRMjMTJ/mopqcp5gS17svk0CROOFXWguBx2vEXv9IZ7blijFgysKen66foQ2ZJaeH3EyoEUy4EEX1jrobWDwgJaUUjABTwGYLA8G5PwBZzuY5ZTgieoc3QDzimguLEh6/puv47ZCit9mAjZVA2o3mc9Liwr1HCxtXM0CYDKU=
  run:
    - "mvn clean package"