language: java
addons:
  sonarcloud:
    organization: mihanloko
    token:
      secure: mqdoawEKQJX6OtLO7XDl+1BXXhmhp0s0dIJDlHNFcsig2JnmZ4hG5PtGOqsVUGTgNkHsNed3W8hEhmlU/zCh33LxJqzhXIwhx7G6oojMQEO2YOoVhcYvFhK+f9g50mwywTnTfZgViB6VVOPWwZ8VDO9gpCNEeM2e7WZ3KZESkb5/TcppZRaqYC9rs38+XNwqcXiWaylUCPsMoZuf+YKrNgmioHvYXCOHV/OdKbgZbqCvQ5fxV3jEqrDctnfAU5P6tnXS/GWsngdiveD8fTPYX7W6ESpdXq74YCrTeVyiqsUGmyJETVXtLG46IN4+zAibmn+QkSiHSAvarFBTW/4cAOd18qwyMxrMg3Zvjkz8eONIe8GUi9I43HD61+G294DtQjiE0laagyq3C2xFH6Nb9WwoWfD8Qe02vCcoMrp9Xm1bQeN37DNKeh6GlsjITU4AY+qWKC8S2AbzqgDaw15V1WCuJPo0CoKJgXjgtvw3C1MRrCcIcxpVwHNAhuo5RmPk40agX5JNek/xWIc7aARGavkc74bfD/2SQe+paaIocVRzQgjsAWOoRq50I4dDtUV2Y4DRQHD+dgY3w6dEpdlT9GsYfB0gP48md2pQOnoemhKWb7m6WXe+NAkPSCurBkTOjo7hLt3yQXpmiEPF6Dq7cOF4sqGtkHVVLA+FPvC/VaE=
script:
- mvn clean package package org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  -Dsonar.projectKey=mihanloko_projectForTeamDev
deploy:
  provider: heroku
  app: test-app-loko
  api_key:
    secure: WX6rayFHa65O0OJnd9uQTKT6Oq5cugR54JBJ2ZDLXPGtRpbjRYNUKYLLUTfHVj/dQAO/0SR23HhyjVJCEKsyNb5GTkd6hxoDgkoRVmTblnvmtOrUquhKkqaWHyIZqqMMghKBUwgxfvcsNAfsBduaQ06chUXCrXNy40dRjGEx7zZJ2P/S3gTZLMlacA6U0YJolkl40UEcWOTAye9C3E7bWk2pHGKvalN+0lyAoQKPsJyj/sNJhKd933gL52nlwgRqYGZTWqKfA9CK1w5wpgYGIJ9WcLG7htLizWoMfjzlt4cENlri/jhEfMMDuoPqnUgkeJ2vIJDFgbHRG8c9Zg4VLiVucYkIx3H12Yv+XuPTUbQrSqvEsCMQ6YGTa3guxZKiQrM9/hXWP8UnmSu9AzNER8PpfY4y86Q3MXw+YSNRrmXRdJrWvsN8e96hBH2JEgCbhdtetnfuUMj6asfOSznWns+/2/nzVpqma3dvDFUVRo4XQVoYSgy4VeIRSFIs294pynRgafCYFNzSSfp3TZudi36WizLE9Kb6/iZs177ow9ddVbOHfMtpEKTvZkLUANn6kAj6c4FPp1TVH+3g5x92W6u17jt6NuddXFHTeJswGgHiwGsS+L8wZxuoO/ulA0VaM+0isZkQ6hGYCqMU7e/yBgQ24D6HBGonKmV4Z780Psk=
  run:
  - mvn clean package
